# Generated by Django 4.2.4 on 2023-10-20 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SensorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ph_value', models.FloatField()),
                ('ec_value', models.FloatField()),
                ('water_temperature', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TargetValues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ec_target', models.FloatField()),
                ('ph_target', models.FloatField()),
                ('n_ratio', models.FloatField()),
                ('p_ratio', models.FloatField()),
                ('k_ratio', models.FloatField()),
                ('pump_rate', models.FloatField()),
                ('pump_rate2', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='ECSettings',
        ),
        migrations.DeleteModel(
            name='ECValue',
        ),
        migrations.DeleteModel(
            name='pHSettings',
        ),
        migrations.DeleteModel(
            name='pHValue',
        ),
        migrations.DeleteModel(
            name='PumpTime',
        ),
    ]
