# Generated by Django 4.2.6 on 2023-11-16 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0002_sensordata_targetvalues_delete_ecsettings_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sensordata',
            old_name='ec_value',
            new_name='ec',
        ),
        migrations.RenameField(
            model_name='sensordata',
            old_name='ph_value',
            new_name='ph',
        ),
        migrations.RenameField(
            model_name='targetvalues',
            old_name='ec_target',
            new_name='target_ec',
        ),
        migrations.RenameField(
            model_name='targetvalues',
            old_name='ph_target',
            new_name='target_ph',
        ),
        migrations.RenameField(
            model_name='targetvalues',
            old_name='pump_rate',
            new_name='target_water_temperature',
        ),
        migrations.RemoveField(
            model_name='targetvalues',
            name='pump_rate2',
        ),
        migrations.RemoveField(
            model_name='targetvalues',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='targetvalues',
            name='pump_time',
            field=models.IntegerField(default=2000),
            preserve_default=False,
        ),
    ]
