# Generated by Django 4.2.6 on 2023-11-16 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0003_rename_ec_value_sensordata_ec_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sensordata',
            old_name='water_temperature',
            new_name='water_temp',
        ),
        migrations.RenameField(
            model_name='targetvalues',
            old_name='target_water_temperature',
            new_name='target_water_temp',
        ),
    ]
