# Generated by Django 4.2.6 on 2023-11-28 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0005_phkalib'),
    ]

    operations = [
        migrations.CreateModel(
            name='EcKalib',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ec_1', models.FloatField()),
                ('ec_2', models.FloatField()),
            ],
        ),
    ]
