# Generated by Django 4.2.4 on 2023-11-30 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0007_eckalib_ec_1_v_eckalib_ec_2_v_eckalib_timestamp_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoKalib',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ec_1_v', models.FloatField()),
                ('ec_2_v', models.FloatField()),
                ('ph_4_v', models.FloatField()),
                ('ph_7_v', models.FloatField()),
            ],
        ),
        migrations.RemoveField(
            model_name='eckalib',
            name='ec_1_v',
        ),
        migrations.RemoveField(
            model_name='eckalib',
            name='ec_2_v',
        ),
        migrations.RemoveField(
            model_name='phkalib',
            name='ph_4_v',
        ),
        migrations.RemoveField(
            model_name='phkalib',
            name='ph_7_v',
        ),
    ]
