# Generated by Django 4.2.4 on 2023-12-01 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0008_vokalib_remove_eckalib_ec_1_v_remove_eckalib_ec_2_v_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vokalib',
            old_name='ec_1_v',
            new_name='ec_v',
        ),
        migrations.RenameField(
            model_name='vokalib',
            old_name='ph_4_v',
            new_name='ph_v',
        ),
        migrations.RemoveField(
            model_name='vokalib',
            name='ec_2_v',
        ),
        migrations.RemoveField(
            model_name='vokalib',
            name='ph_7_v',
        ),
    ]
