# Generated by Django 5.0.1 on 2024-03-29 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0011_calculatedvalues_water_temp'),
    ]

    operations = [
        migrations.CreateModel(
            name='SensorData2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature1', models.FloatField()),
                ('temperature2', models.FloatField()),
                ('humidity1', models.FloatField()),
                ('humidity2', models.FloatField()),
                ('water_temp1', models.FloatField()),
                ('water_temp2', models.FloatField()),
                ('water_level', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
