# Generated by Django 5.0.1 on 2024-03-29 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0012_sensordata2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sensordata2',
            old_name='water_temp1',
            new_name='waterTemp1',
        ),
        migrations.RenameField(
            model_name='sensordata2',
            old_name='water_temp2',
            new_name='waterTemp2',
        ),
    ]
