# Generated by Django 5.0.1 on 2024-03-29 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0013_rename_water_temp1_sensordata2_watertemp1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensordata2',
            name='water_level',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
