# Generated by Django 5.0.1 on 2024-03-29 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0014_alter_sensordata2_water_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='calibration_ec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ec1', models.FloatField()),
                ('ec5', models.FloatField()),
                ('ec12', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='calibration_ph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ph4', models.FloatField()),
                ('ph7', models.FloatField()),
                ('ph9', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='EcKalib',
        ),
        migrations.DeleteModel(
            name='PhKalib',
        ),
        migrations.DeleteModel(
            name='VoKalib',
        ),
    ]
