# Generated by Django 5.0.1 on 2024-03-30 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0015_calibration_ec_calibration_ph_delete_eckalib_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='calibration_ec',
            new_name='CalibrationEc',
        ),
        migrations.RenameModel(
            old_name='calibration_ph',
            new_name='CalibrationPh',
        ),
    ]
