# Generated by Django 5.0.1 on 2024-03-31 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0016_rename_calibration_ec_calibrationec_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='targetvalues',
            name='pump_time',
        ),
        migrations.AddField(
            model_name='targetvalues',
            name='pump_time_ph',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='targetvalues',
            name='pump_time_ratio',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='targetvalues',
            name='k_ratio',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='targetvalues',
            name='n_ratio',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='targetvalues',
            name='p_ratio',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='targetvalues',
            name='target_ec',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='targetvalues',
            name='target_ph',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='targetvalues',
            name='target_water_temp',
            field=models.FloatField(default=0),
        ),
    ]
