# Generated by Django 5.0.1 on 2024-03-31 00:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0017_remove_targetvalues_pump_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='targetvalues',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='targetvalues',
            name='k_ratio',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='targetvalues',
            name='n_ratio',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='targetvalues',
            name='p_ratio',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='targetvalues',
            name='pump_time_ph',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='targetvalues',
            name='pump_time_ratio',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='targetvalues',
            name='target_ec',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='targetvalues',
            name='target_ph',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='targetvalues',
            name='target_water_temp',
            field=models.FloatField(),
        ),
    ]
