# Generated by Django 5.0.1 on 2024-04-01 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0019_targetec_targetph_targetratio_targetwt_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrenzwerteSensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ph_min', models.FloatField()),
                ('ph_max', models.FloatField()),
                ('ec_min', models.FloatField()),
                ('ec_max', models.FloatField()),
                ('temp_min', models.FloatField()),
                ('temp_max', models.FloatField()),
                ('humd_min', models.FloatField()),
                ('humd_max', models.FloatField()),
                ('water_level_max', models.CharField(blank=True, max_length=255, null=True)),
                ('water_level_min', models.CharField(blank=True, max_length=255, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
