# Generated by Django 5.0.1 on 2024-04-03 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0020_grenzwertesensor'),
    ]

    operations = [
        migrations.AddField(
            model_name='grenzwertesensor',
            name='temp_wt_max',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='grenzwertesensor',
            name='temp_wt_min',
            field=models.FloatField(default=0),
        ),
    ]
