# Generated by Django 5.0.1 on 2024-04-04 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0022_grenzwertesensorec_grenzwertesensorhumd_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grenzwertesensorec',
            options={'get_latest_by': 'timestamp'},
        ),
        migrations.AlterModelOptions(
            name='grenzwertesensorhumd',
            options={'get_latest_by': 'timestamp'},
        ),
        migrations.AlterModelOptions(
            name='grenzwertesensorph',
            options={'get_latest_by': 'timestamp'},
        ),
        migrations.AlterModelOptions(
            name='grenzwertesensortemp',
            options={'get_latest_by': 'timestamp'},
        ),
        migrations.AlterModelOptions(
            name='grenzwertesensorwaterlevel',
            options={'get_latest_by': 'timestamp'},
        ),
        migrations.AlterModelOptions(
            name='grenzwertesensorwt',
            options={'get_latest_by': 'timestamp'},
        ),
    ]
