# Generated by Django 5.0.1 on 2024-04-04 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0023_alter_grenzwertesensorec_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='calculatedvalues',
            options={'get_latest_by': 'timestamp'},
        ),
        migrations.AlterModelOptions(
            name='sensordata2',
            options={'get_latest_by': 'timestamp'},
        ),
    ]
