# Generated by Django 5.0.1 on 2024-04-11 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0024_alter_calculatedvalues_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrenzwerterSensorGas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gas_grenzwert', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'get_latest_by': 'timestamp',
            },
        ),
        migrations.DeleteModel(
            name='GrenzwerteSensorWaterLevel',
        ),
        migrations.AddField(
            model_name='sensordata2',
            name='Waterflow',
            field=models.FloatField(default=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sensordata2',
            name='gas_sensor',
            field=models.FloatField(default=300),
            preserve_default=False,
        ),
    ]
