# Generated by Django 5.0.1 on 2024-04-11 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0025_grenzwertersensorgas_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrenzwerteWaterflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waterflow_grenzwert', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'get_latest_by': 'timestamp',
            },
        ),
    ]
