# Generated by Django 5.0.1 on 2024-04-13 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0026_grenzwertewaterflow'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensordata2',
            name='lightIntensity',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
