# Generated by Django 5.0.1 on 2024-05-25 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0028_humdrelaytimer_lichtrelaytimer_test2relaytimer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SensorDataOutdoor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature01', models.FloatField()),
                ('humidity01', models.FloatField()),
                ('temperature02', models.FloatField()),
                ('humidity02', models.FloatField()),
                ('temperature03', models.FloatField()),
                ('humidity03', models.FloatField()),
                ('moisture01', models.FloatField()),
                ('moisture02', models.FloatField()),
                ('moisture03', models.FloatField()),
                ('soil_temp01', models.FloatField()),
                ('soil_temp02', models.FloatField()),
                ('soil_temp03', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'get_latest_by': 'timestamp',
            },
        ),
    ]
