# Generated by Django 5.0.1 on 2024-05-26 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0030_targethumd_targettemp'),
    ]

    operations = [
        migrations.CreateModel(
            name='SensorMoisture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moisture01', models.FloatField()),
                ('moisture02', models.FloatField()),
                ('moisture03', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'get_latest_by': 'timestamp',
            },
        ),
        migrations.RemoveField(
            model_name='sensordataoutdoor',
            name='moisture01',
        ),
        migrations.RemoveField(
            model_name='sensordataoutdoor',
            name='moisture02',
        ),
        migrations.RemoveField(
            model_name='sensordataoutdoor',
            name='moisture03',
        ),
    ]
