# Generated by Django 5.0.1 on 2024-05-26 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0031_sensormoisture_remove_sensordataoutdoor_moisture01_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Relay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('run_time', models.IntegerField(default=0)),
                ('pause_time', models.IntegerField(default=0)),
            ],
        ),
    ]
