# Generated by Django 5.0.1 on 2024-05-28 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0032_relay'),
    ]

    operations = [
        migrations.CreateModel(
            name='TargetHumid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_humidity', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
