# Generated by Django 5.0.1 on 2024-05-31 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0034_waterlevelhumid_watervolume_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='targetph',
            name='pump_time_ph',
            field=models.FloatField(),
        ),
    ]
