# Generated by Django 5.0.1 on 2024-05-31 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0035_alter_targetph_pump_time_ph'),
    ]

    operations = [
        migrations.AlterField(
            model_name='targetratio',
            name='pump_time_ratio',
            field=models.FloatField(),
        ),
    ]
