# Generated by Django 5.0.1 on 2024-06-01 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0036_alter_targetratio_pump_time_ratio'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensordata2',
            name='pressure1',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sensordata2',
            name='pressure2',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
