# Generated by Django 5.0.1 on 2024-06-04 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0037_sensordata2_pressure1_sensordata2_pressure2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensordata2',
            name='gas_sensor',
        ),
        migrations.RemoveField(
            model_name='sensordata2',
            name='lightIntensity',
        ),
    ]
