# Generated by Django 5.0.1 on 2024-06-06 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0038_remove_sensordata2_gas_sensor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensordata2',
            name='soil_moisture1',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sensordata2',
            name='soil_moisture2',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
