# Generated by Django 5.0.1 on 2024-06-07 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0039_sensordata2_soil_moisture1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentPhase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase', models.CharField(default='wachstum', max_length=20)),
            ],
        ),
    ]
