# Generated by Django 5.0.1 on 2024-06-07 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0041_pumpstatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='SensorSoilMoisture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soil_moisture1', models.FloatField()),
                ('soil_moisture2', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'get_latest_by': 'timestamp',
            },
        ),
    ]
