# Generated by Django 5.0.1 on 2024-06-07 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0042_sensorsoilmoisture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensordata2',
            name='soil_moisture1',
        ),
        migrations.RemoveField(
            model_name='sensordata2',
            name='soil_moisture2',
        ),
    ]
