# Generated by Django 5.0.1 on 2024-06-09 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0045_targethumid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HumdRelayTimer',
        ),
        migrations.DeleteModel(
            name='LichtRelayTimer',
        ),
        migrations.DeleteModel(
            name='Test2RelayTimer',
        ),
        migrations.DeleteModel(
            name='TestRelayTimer',
        ),
    ]
