# Generated by Django 5.0.1 on 2024-06-19 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0046_delete_humdrelaytimer_delete_lichtrelaytimer_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sensorsoilmoisture',
            old_name='soil_moisture1',
            new_name='soilMoisture1',
        ),
        migrations.RenameField(
            model_name='sensorsoilmoisture',
            old_name='soil_moisture2',
            new_name='soilMoisture2',
        ),
    ]
