# Generated by Django 5.0.1 on 2024-06-19 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0047_rename_soil_moisture1_sensorsoilmoisture_soilmoisture1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sensordata2',
            old_name='Waterflow',
            new_name='flowRate',
        ),
    ]
